#define HAS_ATTRIBUTE_UNUSED 1
#define HAS_ATTRIBUTE_DEPRECATED 1
#define HAS_ATTRIBUTE_DEPRECATED_MSG 1
/* #undef HAVE_ARRAY */
/* #undef HAVE_BOOST_MAKE_SHARED_HPP */
/* #undef HAVE_BOOST_SHARED_PTR_HPP */
#define HAVE_DUNE_BOOST 1
#define HAVE_GMP 1
/* #undef HAVE_MAKE_SHARED */
/* #undef HAVE_MPI */
/* #undef HAVE_NULLPTR */
/* #undef HAVE_STATIC_ASSERT */
/* #undef HAVE_SHARED_PTR */
/* #undef MPI_2 */
/* #undef SHARED_PTR_HEADER */
/* #undef SHARED_PTR_NAMESPACE */
/* #undef HAVE_TYPE_TRAITS */
/* #undef HAVE_TR1_TUPLE */
/* #undef HAVE_TUPLE */
#define HAVE_CXA_DEMANGLE 1
/* #undef HAVE_BOOST_FUSION */
/* #undef HAVE_MEM_USAGE_T_EXPANSIONS */
/* #undef HAVE_PARDISO */
#define HAVE_BOOST 1
/* #undef HAVE_PARMETIS */
#define HAVE_SUPERLU 1
#define HAVE_UMFPACK 1
#define HAVE_SUITESPARSE_UMFPACK 1
#define SUPERLU_INT_TYPE int
/* #undef HAVE_SLU_CDEFS_H */
#define HAVE_SLU_DDEFS_H 1
/* #undef HAVE_SLU_SDEFS_H */
/* #undef HAVE_SLU_ZDEFS_H */
#define SUPERLU_MIN_VERSION_4_3 1
#define SUPERLU_MIN_VERSION_5 1
#define SUPERLU_POST_2005_VERSION 1
/* #undef HAVE_ALGLIB */
/* #undef HAVE_UG */
/* #undef HAVE_GRIDTYPE */
/* #undef HAVE_GRAPE */
/* #undef HAVE_PSURFACE */
/* #undef HAVE_AMIRAMESH */
#define HAVE_ALBERTA 1
/* #undef HAVE_STDINT_H */
#define DUNE_GRID_EXPERIMENTAL_GRID_EXTENSIONS 1
#define DUNE_ALBERTA_VERSION 0x300
#define HAVE_DUNE_ALUGRID 1
#define HAVE_METIS 1
#define HAVE_ZLIB 1
/* #undef HAVE_ZOLTAN */
#define HAVE_OPENMP 1
#define HAVE_VALGRIND 1
/* #undef HAVE_FINAL */
#define HAVE_ECL_INPUT 1
#define DUNE_GRID_VERSION_MAJOR 2
#define DUNE_GRID_VERSION_MINOR 9
#define DUNE_GRID_VERSION_REVISION 1
#define DUNE_GEOMETRY_VERSION_MAJOR 2
#define DUNE_GEOMETRY_VERSION_MINOR 9
#define DUNE_GEOMETRY_VERSION_REVISION 1
#define DUNE_COMMON_VERSION_MAJOR 2
#define DUNE_COMMON_VERSION_MINOR 9
#define DUNE_COMMON_VERSION_REVISION 1
#define HAVE_DUNE_ISTL 1
#define HAVE_PTSCOTCH 1
#define IS_SCOTCH_METIS_HEADER 0
#define HAVE_OPM_COMMON 1
#define HAVE_OPM_GRID 1
#define HAVE_PTHREAD 1
/* #undef HAVE_EWOMS */
/* #undef HAVE_PETSC */
#define COMPILE_BDA_BRIDGE 1
/* #undef HAVE_CUDA */
#define HAVE_OPENCL 1
#define HAVE_OPENCL_HPP 1
#define HAVE_AMGCL 1
#define HAVE_VEXCL 1
/* #undef HAVE_ROCALUTION */
/* #undef HAVE_ROCSPARSE */
#define HAVE_SUITESPARSE_UMFPACK_H 1
#define HAVE_DUNE_COMMON 1
/* #undef DUNE_ISTL_WITH_CHECKING */
#define DUNE_ISTL_VERSION_MAJOR 2
#define DUNE_ISTL_VERSION_MINOR 9
#define DUNE_ISTL_VERSION_REVISION 1
/* #undef HAVE_DAMARIS */
#define HAVE_HDF5 1
/* #undef USE_HIP */
/* #undef USE_TRACY */
/* #undef FLOW_INSTANTIATE_FLOAT */
#define HAVE_FLOATING_POINT_FROM_CHARS 1
#define DUNE_FEM_VERSION_MAJOR 2
#define DUNE_FEM_VERSION_MINOR 9
#define DUNE_FEM_VERSION_REVISION 1
#define HAVE_DYNAMIC_BOOST_TEST 1
